name: CMP Build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      source: ${{ steps.filter.outputs.source }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            source:
              - 'composeApp/src/**/*.kt'
              - 'composeApp/src/**/*.java'

  build:
    uses: ./.github/workflows/build.yml

  spotless:
    uses: ./.github/workflows/spotless.yml
    permissions:
      contents: write

  unit-tests:
    needs: [ detect-changes, build ]
    if: needs.detect-changes.outputs.source == 'true'
    uses: ./.github/workflows/unit-tests.yml

  instrumented-tests:
    needs: [ detect-changes, build ]
    if: needs.detect-changes.outputs.source == 'true'
    uses: ./.github/workflows/instrumented-tests.yml

  coverage:
    needs: [ unit-tests, instrumented-tests ]
    uses: ./.github/workflows/coverage.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
